version: "3.8"

services:
  mysql_db:
    image: mysql:8.0
    container_name: invoice_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Firdous@270403
      MYSQL_DATABASE: invoice_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: invoice_backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/invoice_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Firdous@270403

  frontend:
    build: ./frontend
    container_name: invoice_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api

volumes:
  db_data:
